### ISSUE TITLE
Autoload failing

### ISSUE THREAD

**Issue by neyl** [voku/php-hooks#8]
Latest commit to change autoload to psr-4 is causing my project to fail initialising. Reason is because, the files are in src/voku/helper and psr-4 means that the given namespace can be found in given dir. So Hooks.php should now be moved to src dir.
Please test this for yourself and fix - my project stopped working after composer update and we depend on you! THANKS!!

**Comment by voku** [comment]
fixed, I didn't saw the error, because I used the optimize-option from composer in production. And in the tests there was a require() for the "Hook"-Class :/ ... Sorry for that! Test and Autoloader should be fixed now + new git tag
